php:
  envVars:
    - name: APP_KEY
      value: "base64:HcqG2d5UXtnOkP+nOxz/cZhnwff2XX5bC+pEjX2ZIbY="
    - name: DB_DATABASE
      value: "laravel"
    - name: DB_USERNAME
      value: "nnphat6492"
    - name: DB_PASSWORD
      value: "Ngu9enph@t"


