php:
  repository: "nnphat6492/laravel-kubernetes"
  tag: "latest"
  fpmEnabled: false
  envVars:
    - name: APP_ENV
      value: production
    - name: APP_DEBUG
      value: false
    - name: DB_PORT
      value: 31333
    - name: DB_HOST
      value: 139.59.242.248
